project_id = "fjquufgbnxyocmuzltxi"

[db.migrations]
enabled = false

[edge_runtime]
enabled = true
policy = "per_worker"

[functions.v2-api]
enabled = true
verify_jwt = false
entrypoint = "./functions/v2-api/bundle.mjs"
import_map = "./functions/v2-api/deno.json"

[functions.v2-api-perf]
enabled = true
verify_jwt = false
entrypoint = "./functions/v2-api-perf/bundle.mjs"
import_map = "./functions/v2-api-perf/deno.json"
