"""Finite generated build projection while the first online release is pending.

Only the sealed 0a03 -> 28a3 online integration delta is removed. This module
never edits a Git checkout, changes the database, authorizes a release, or starts
an engine. Its caller must separately establish the pending-migration origin.
The original candidate commit/tree and every generated byte remain in the proof.
"""

import difflib
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import subprocess

BASELINE_COMMIT = '0a03fa28e6b844a18833d5c63f1de700f091fc64'
BASELINE_TREE = '668ca1570a8e4898e7f473198087ec549c270239'
ONLINE_COMMIT = '28a3ba4ffd17d36001b1104c97394f5ae871d73d'
ONLINE_TREE = '014959a59519da585928adaa7f76f7236e1786d1'
CONTEXT_PATH = '.deploy/production-release/api-admin-pending-build-context'
RECORD_PATH = '.deploy/production-release/api-admin-pending-build-projection.json'
RUNTIME_FILES = ('apps/api/prisma-mysql/schema.prisma',
                 'apps/api/prisma-mysql/seed.ts', 'docker-compose.aws-mysql.yml')
ONLINE_SOURCE_SEALS = {
    'apps/api/src/id-business-v2/online-recharge':
        '338adfad51001a88fe0b77f1415c0a232548d38d49993766955a970aea6e3e0c',
    'apps/admin/src/v2/features/online-recharge':
        '0e1abd3800877af9a2152f946952447f785b0a45d581730e2dbb7fa40b419d24'}
REMOVED_FILE_SEALS = {
    'apps/api/src/auth/login-events.ts':
        '7225280c4b77bad54596a11f65ee9ce322395f0d51232f2bbbb5fe9ee55cb980',
    'apps/api/src/auth/login-events.spec.ts':
        '28de6782a7f0635518f98cfa320f79586df5e0f4a17d3ac6d6b010b1334f0387',
    'apps/api/prisma-mysql/migrations/20261009093000_online_recharge/migration.sql':
        '44966182c1bf38290b01f665a4c2c863b052677c5e0024b900137f1d7f11eb95'}
# Reviewed Git blobs, not hashes learned from a mutable release directory.
FILE_SEALS = {
    '.dockerignore': (
        '4fb657af9c480776b40f2957b6cbb87d0e95a82842b3b00fcdc75fcacc67c562',
        'e639582e470b6869d9f1b7c45490f1f5a624b71389a92b002f2daa043b735580'),
    'apps/admin/src/v2-router.ts': (
        'e27df135b0763446ac505924b123cbdbcafc2fb5246865922f70ae875ed24bdc',
        '7b44972c05af6d4e8bed74da41b7ad38813e27fbd9edf415cc84d7bcf9298b9f'),
    'apps/admin/src/v2/features/feature.ts': (
        '7893f1ce70f86f0cee3918c9ea184b48d629a8a5c7598b1eaa773e6affb27805',
        '17d20386d89d3636c70f17670de9f5673e4ad76d8bea601d603f58c8a82a1066'),
    'apps/admin/src/v2/features/registry.spec.ts': (
        '22fcf80cae35bb02b20a46d6eca699a28336162e82b673cfde8cec577d6a15c9',
        '237da7c6efec27f6f00113ae500ab1ca9b9e953b63527d45612e12f8852a4354'),
    'apps/admin/src/v2/features/registry.ts': (
        '9b544dd1975471f5f16d9b67e96bdeb2e48893416f81d7a61a9a011ff3b39bec',
        '46a013861de638a1fe91a76c36f7db348ae91eff4ce6a6e6d0d73dc6a0cbfa12'),
    'apps/admin/src/v2/features/roles/rolePermissionWorkspace.ts': (
        '4b278ef98d920f48e2136452fc2a523e19b8b1c3ba221930a6295c3c8b54e949',
        '655b9f504622beed8544674577ef8008ee082a5f162e74e3170545bde237c69b'),
    'apps/admin/src/v2/features/tableSchemas.ts': (
        '0beb529272423800122cd338ebb3259a53b22b6a15a0a7f903aeb388c4a596ae',
        'eae700cc77be638e6bf3203ae07f8d9cb30f09fe639baff659b109f15aa67eb5'),
    'apps/admin/src/v2/layouts/V2AdminLayout.vue': (
        'ccd9017e751af9ef088e96b0741620fb6d2fefba3e592113b766f4d956326bc8',
        'f8d0e3bdcea7c1ac0531632ba17b5d8829b63797f0bb96da945bfa15c28bcb98'),
    'apps/api/Dockerfile.mysql': (
        '5cd802121f63cf1a65742bd0b3b449235c4af6a079606f1c347a91bb3a3e6c3c',
        '2a14141ad592bfe56484980c03dfb7e9967adc97036b9486f4cc834dbf90663d'),
    'apps/api/package.json': (
        'a5af77f656281999f8c750f33e7740be7ae78b429c28c129d5348eb4e3d2bc79',
        'f8a9cd054478af472964facc3b70012fef70a3e63f0b55376582d57e691acd2c'),
    'apps/api/prisma-mysql/schema.prisma': (
        '8006d3ce6f0b44cf62f3b47bb7b4a0b14d0ddc18ddf113a5da34a901b62fb197',
        '8ae09e883e79bfb85cd65edbf630f2ec03b6b397eb46d172b4c4f05514b715a7'),
    'apps/api/prisma-mysql/seed.ts': (
        'ac9940a7977def1ed6eaad38ed154d81963ce6e877f02ffc07234fa61591096b',
        '2a7becbe8da189adad73b30d7bfe36070fd44ae4f683f7e4a01178d14ae08b5b'),
    'apps/api/src/auth/auth.service.spec.ts': (
        'fa08d5783c50525ea9c3d22919bdeb21bddc84a8d6e1139fb2cfd7f155b8a4ad',
        '6799a3cc9cfafad1bd27cca49ce59513a703aedecf33bae6804b4a39e0fa28f3'),
    'apps/api/src/auth/auth.service.ts': (
        '526081c0fb0d1a26d7da727cd4f2cce459493cc10d4375396beff2a7aa2fd137',
        '39ec0a628c914acc244aaf8c8e3d0f7368fbbeef15092f697a71c02ba8226c4e'),
    'apps/api/src/auth/auth.types.ts': (
        'a1ee8414ce029a72954146fe36081768bee6a6101d380bc40b3ccb633ff7d43a',
        '08fdc046039777741cbaa059cbd3cdcb29cbcbc020d98cf08016c0096798cfb7'),
    'apps/api/src/id-business-v2/id-business-v2.module.ts': (
        '5608a90bf5bf65a750c2222670bdb4073ca7c2a63a40d00c812db1b1da0e864c',
        '85bc608f18cb4f08b1420561d2d4069e17c5d8dfecc58e571f33b741768cb507'),
    'apps/api/src/id-business-v2/sensitive-access/id-business-v2-sensitive-access.catalog.ts': (
        '990dc5058757d671eb61409f811fbcf73016ccea7cf05043acb275451cc1a428',
        '68bed2597aa5eff870695ddcf07c7dc95a31b27f8aeaa3ad419628f6ced1ca13'),
    'apps/api/src/main.ts': (
        'de7c844267297f04336a74afcebd714195659513097b8da4d2af2a0cdd780865',
        '39afb00315abaca2e734692c894729d7b43c98c7c2cc9a423b2decf6bc92a5ae'),
    'apps/api/src/v2-auth/v2-auth.module.ts': (
        '882a938af6a88ec6f73ec477fefeaf5ca80b6087cde4d9484f217c0bd2624f66',
        '03462fd8bf1a1cfdc220cf5c06ab52157b96647d6f5fcd1ee2f43dc98be4875e'),
    'apps/api/src/v2-auth/v2-identity.service.spec.ts': (
        'a704591a9b934f813a2ea48f1fb682e08b99f19e96be3ef7f8a19978d50d4003',
        '2c8aa97a9b61f4cb7fe803a8158ebb72e0884e6c82e4a32f344fc19dc2544539'),
    'apps/api/src/v2-auth/v2-identity.service.ts': (
        '58e1386bcab5d536ce35fda9e49a3a97392caabeaae3fe86fec6dc6ed9fb43c0',
        'eee499fa7eb586781c26a42585395837ee4d74ec8ccec7b4b6204b78960f4392'),
    'docker-compose.aws-mysql.yml': (
        '953c6264f157b00218f2a019d5e2c0b6bc4a34f687f2ec42ad782e0009e7672c',
        '8250b0b74da9271e4254448dd97c53b30129f6e37e9fc5203ccd1a01200c2792'),
    'deploy/nginx/admin.conf': (
        '09574c9e30d366de734511fbef4b1d7d907d6b733af74d8e6b03d1b5878a168e',
        '5bc80e906215c63ee0bf79f123d672dbba604e03aad94f0eb444a03a9664b1da'),
    'package-lock.json': (
        '024e748629a0a9cb9de5306e84c259173d9af0d0cca8b7b51c2722ad9c1b4785',
        '6104c1be6681361d002145c15c8bd1a15a9741a3b61a4694b3982daf7ba5b70f'),
    'package.json': (
        'f03f604c4a3228f23a9b8c11f1828d4be8759df5a244ece08bbb2e357ca74e36',
        '569ed2d2bd3849ae7c79ea07f860ec1a66de90fc0161681df9064a7332091faf'),
    'packages/shared/src/v2/data-scopes.ts': (
        'd0cf617d90e376a2347269f7bd8f4e5ee793867e18066888a3d9142d8d7f608a',
        'bd3f9fa675f0848146127621b3356d41f4695f5a9c84ae5b27e3a19c0e1c1531'),
}


def require(condition, code):
    if not condition:
        raise RuntimeError('API_ADMIN_PENDING_' + code)


def fingerprint(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def _valid_name(name):
    return (isinstance(name, str) and name and '\\' not in name and '\x00' not in name
            and not PurePosixPath(name).is_absolute()
            and not any(part in ('', '.', '..', '.git') for part in name.split('/'))
            and PurePosixPath(name).as_posix() == name)


def inventory(files):
    require(isinstance(files, dict) and 0 < len(files) < 100000, 'SOURCE_INVALID')
    rows, total = {}, 0
    for name, row in files.items():
        require(_valid_name(name) and isinstance(row, tuple) and len(row) == 2
                and isinstance(row[0], bytes) and len(row[0]) <= 8 * 1024 * 1024
                and row[1] in ('100644', '100755'), 'SOURCE_INVALID')
        total += len(row[0])
        rows[name] = {'mode': row[1], 'sha256': hashlib.sha256(row[0]).hexdigest()}
    require(total <= 64 * 1024 * 1024, 'SOURCE_TOO_LARGE')
    return rows


def source_tree(files):
    """Recompute the complete immutable archive's Git tree, including modes."""
    inventory(files)
    entries = {}
    for name, (raw, mode) in files.items():
        parent = entries
        parts = name.split('/')
        for part in parts[:-1]:
            require(part not in parent or isinstance(parent[part], dict), 'SOURCE_INVALID')
            parent = parent.setdefault(part, {})
        require(parts[-1] not in parent, 'SOURCE_INVALID')
        parent[parts[-1]] = (mode, hashlib.sha1(b'blob ' + str(len(raw)).encode() + b'\0' + raw).digest())

    def encode(items):
        raw = b''
        for name, value in sorted(items.items(), key=lambda item:
                                  (item[0] + '/' if isinstance(item[1], dict) else item[0]).encode()):
            mode, oid = ('40000', encode(value)) if isinstance(value, dict) else value
            raw += mode.encode() + b' ' + name.encode() + b'\0' + oid
        return hashlib.sha1(b'tree ' + str(len(raw)).encode() + b'\0' + raw).digest()

    return encode(entries).hex()


def _directory_files(files, root):
    return {name[len(root) + 1:]: row for name, row in files.items() if name.startswith(root + '/')}


def validate_references(baseline, online):
    require(source_tree(baseline) == BASELINE_TREE and source_tree(online) == ONLINE_TREE,
            'REFERENCE_TREE_CHANGED')
    for name, (before, after) in FILE_SEALS.items():
        require(name in baseline and name in online
                and baseline[name][1] == online[name][1] == '100644'
                and hashlib.sha256(baseline[name][0]).hexdigest() == before
                and hashlib.sha256(online[name][0]).hexdigest() == after,
                'REFERENCE_FILE_CHANGED')
    for root, digest in ONLINE_SOURCE_SEALS.items():
        rows = _directory_files(online, root)
        require(not _directory_files(baseline, root) and rows
                and fingerprint({n: hashlib.sha256(r[0]).hexdigest() for n, r in rows.items()}) == digest,
                'REFERENCE_DIRECTORY_CHANGED')
    for name, digest in REMOVED_FILE_SEALS.items():
        require(name not in baseline and name in online and online[name][1] == '100644'
                and hashlib.sha256(online[name][0]).hexdigest() == digest, 'REFERENCE_FILE_CHANGED')


def _inverse_delta(candidate, before, after):
    """Apply only exact, unique online hunks; never use fuzzy patch offsets.

    Three unchanged lines on each side bind replacements to their original
    integration point. A later intersecting change or repeated hunk is rejected.
    Unrelated bytes outside these sealed fragments are retained verbatim.
    """
    before_lines, after_lines = before.splitlines(keepends=True), after.splitlines(keepends=True)
    matcher = difflib.SequenceMatcher(None, before_lines, after_lines, autojunk=False)
    fragments = []
    for group in matcher.get_grouped_opcodes(3):
        previous = b''.join(before_lines[group[0][1]:group[-1][2]])
        introduced = b''.join(after_lines[group[0][3]:group[-1][4]])
        require(introduced and introduced != previous and after.count(introduced) == 1
                and candidate.count(introduced) == 1, 'DELTA_INTERSECTION')
        fragments.append((candidate.index(introduced), introduced, previous))
    require(fragments, 'DELTA_UNAVAILABLE')
    ordered = sorted(fragments)
    require(all(left[0] + len(left[1]) <= right[0] for left, right in zip(ordered, ordered[1:])),
            'DELTA_INTERSECTION')
    result = candidate
    for offset, introduced, previous in reversed(ordered):
        result = result[:offset] + previous + result[offset + len(introduced):]
    return result


def project_files(candidate, baseline, online, candidate_commit, candidate_tree):
    """Pure projection of an already downloaded, exact candidate Git archive."""
    require(isinstance(candidate_commit, str) and re.fullmatch(r'[a-f0-9]{40}', candidate_commit)
            and candidate_commit not in (BASELINE_COMMIT, ONLINE_COMMIT)
            and isinstance(candidate_tree, str) and re.fullmatch(r'[a-f0-9]{40}', candidate_tree),
            'CANDIDATE_IDENTITY_INVALID')
    candidate_rows = inventory(candidate)
    require(source_tree(candidate) == candidate_tree, 'CANDIDATE_TREE_CHANGED')
    validate_references(baseline, online)
    result = dict(candidate)
    generated = {}
    for name in FILE_SEALS:
        require(name in result and result[name][1] == online[name][1], 'INPUT_FILE_CHANGED')
        # Runtime configuration must remain the precise, previously published
        # configuration; there is no implicit schema/seed/Compose extension.
        if name in RUNTIME_FILES:
            require(result[name] == online[name], 'RUNTIME_INPUT_CHANGED')
        raw = _inverse_delta(result[name][0], baseline[name][0], online[name][0])
        if name in RUNTIME_FILES:
            require(raw == baseline[name][0], 'RUNTIME_OUTPUT_CHANGED')
        generated[name] = {'before': candidate_rows[name],
                           'after': {'mode': result[name][1], 'sha256': hashlib.sha256(raw).hexdigest()}}
        result[name] = (raw, result[name][1])
    removed, directories = {}, {}
    for root, digest in ONLINE_SOURCE_SEALS.items():
        current, expected = _directory_files(candidate, root), _directory_files(online, root)
        require(current == expected, 'INPUT_DIRECTORY_CHANGED')
        directories[root] = {'fileCount': len(current), 'sourceSha256': digest,
                             'inventorySha256': fingerprint(inventory(current))}
        for relative in current:
            name = root + '/' + relative
            removed[name] = candidate_rows[name]
            del result[name]
    for name in REMOVED_FILE_SEALS:
        require(candidate.get(name) == online[name], 'INPUT_FILE_CHANGED')
        removed[name] = candidate_rows[name]
        del result[name]
    output_rows = inventory(result)
    unchanged = {name: row for name, row in candidate_rows.items()
                 if name not in generated and name not in removed}
    require(all(output_rows[name] == row for name, row in unchanged.items())
            and set(output_rows) == set(unchanged) | set(generated), 'UNRELATED_SOURCE_CHANGED')
    record = {'version': 1, 'scope': 'API_ADMIN_PENDING_ONLINE_PROJECTION',
              'candidateCommit': candidate_commit, 'candidateTree': candidate_tree,
              'baselineCommit': BASELINE_COMMIT, 'baselineTree': BASELINE_TREE,
              'onlineCommit': ONLINE_COMMIT, 'onlineTree': ONLINE_TREE,
              'contextPath': CONTEXT_PATH, 'candidateFilesSha256': fingerprint(candidate_rows),
              'outputTree': source_tree(result), 'outputFilesSha256': fingerprint(output_rows),
              'unchangedFilesSha256': fingerprint(unchanged), 'generatedFiles': generated,
              'removedFiles': removed, 'removedDirectories': directories,
              'runtimeFiles': list(RUNTIME_FILES)}
    record['projectionSha256'] = fingerprint(record)
    return result, record


def _validate_record(record):
    fields = {'version', 'scope', 'candidateCommit', 'candidateTree', 'baselineCommit', 'baselineTree',
              'onlineCommit', 'onlineTree', 'contextPath', 'candidateFilesSha256', 'outputTree',
              'outputFilesSha256', 'unchangedFilesSha256', 'generatedFiles', 'removedFiles',
              'removedDirectories', 'runtimeFiles', 'projectionSha256'}
    require(isinstance(record, dict) and set(record) == fields and type(record['version']) is int
            and record['version'] == 1 and record['scope'] == 'API_ADMIN_PENDING_ONLINE_PROJECTION'
            and record['baselineCommit'] == BASELINE_COMMIT and record['baselineTree'] == BASELINE_TREE
            and record['onlineCommit'] == ONLINE_COMMIT and record['onlineTree'] == ONLINE_TREE
            and record['contextPath'] == CONTEXT_PATH and record['runtimeFiles'] == list(RUNTIME_FILES)
            and isinstance(record['generatedFiles'], dict) and set(record['generatedFiles']) == set(FILE_SEALS)
            and isinstance(record['removedFiles'], dict) and isinstance(record['removedDirectories'], dict)
            and set(record['removedDirectories']) == set(ONLINE_SOURCE_SEALS), 'RECORD_CHANGED')
    require(all(isinstance(record[key], str) and re.fullmatch(r'[a-f0-9]{40}', record[key])
                for key in ('candidateCommit', 'candidateTree', 'outputTree'))
            and record['candidateCommit'] not in (BASELINE_COMMIT, ONLINE_COMMIT)
            and all(isinstance(record[key], str) and re.fullmatch(r'[a-f0-9]{64}', record[key])
                    for key in ('candidateFilesSha256', 'outputFilesSha256', 'unchangedFilesSha256',
                                'projectionSha256')), 'RECORD_CHANGED')

    def sealed_row(row):
        return (isinstance(row, dict) and set(row) == {'mode', 'sha256'}
                and row['mode'] in ('100644', '100755')
                and isinstance(row['sha256'], str) and re.fullmatch(r'[a-f0-9]{64}', row['sha256']))

    require(all(isinstance(row, dict) and set(row) == {'before', 'after'}
                and sealed_row(row['before']) and sealed_row(row['after'])
                and row['before']['mode'] == row['after']['mode'] == '100644'
                for row in record['generatedFiles'].values()), 'RECORD_CHANGED')
    require(all(_valid_name(name) and sealed_row(row)
                and (name in REMOVED_FILE_SEALS or any(name.startswith(root + '/')
                                                      for root in ONLINE_SOURCE_SEALS))
                for name, row in record['removedFiles'].items())
            and set(REMOVED_FILE_SEALS) <= set(record['removedFiles']), 'RECORD_CHANGED')
    for root, expected in ONLINE_SOURCE_SEALS.items():
        row = record['removedDirectories'][root]
        rows = {name[len(root) + 1:]: r for name, r in record['removedFiles'].items()
                if name.startswith(root + '/')}
        require(isinstance(row, dict) and set(row) == {'fileCount', 'sourceSha256', 'inventorySha256'}
                and type(row['fileCount']) is int and row['fileCount'] == len(rows) and rows
                and row['sourceSha256'] == expected and row['inventorySha256'] == fingerprint(rows)
                and fingerprint({name: r['sha256'] for name, r in rows.items()}) == expected,
                'RECORD_CHANGED')
    require(all(record['removedFiles'][name] == {'mode': '100644', 'sha256': digest}
                for name, digest in REMOVED_FILE_SEALS.items()), 'RECORD_CHANGED')
    for name in RUNTIME_FILES:
        require(record['generatedFiles'][name] == {
            'before': {'mode': '100644', 'sha256': FILE_SEALS[name][1]},
            'after': {'mode': '100644', 'sha256': FILE_SEALS[name][0]}}, 'RECORD_CHANGED')
    require(record['projectionSha256'] == fingerprint({key: value for key, value in record.items()
                                                      if key != 'projectionSha256'}), 'RECORD_CHANGED')
    return record


def validate_record(d, record, candidate_commit, candidate_tree):
    """Pure transport/build-proof check; never downloads or reads production.

    The controller argument keeps the existing scope helper calling convention.
    Runtime staging must additionally call runtime_config_files to reconstruct
    the entire projection from immutable archives, not trust this shape check.
    """
    _validate_record(record)
    require(record['candidateCommit'] == candidate_commit and record['candidateTree'] == candidate_tree,
            'RECORD_IDENTITY_CHANGED')
    return record


def source_references(d):
    # No production Git dependency. Both immutable archives are checked against
    # their full Git trees and each finite input seal on every invocation.
    cached = getattr(d, '_apiAdminPendingProjectionReferences', None)
    if cached is None:
        cached = tuple(d.registration_archive(d.registration_download(commit), commit)
                       for commit in (BASELINE_COMMIT, ONLINE_COMMIT))
        d._apiAdminPendingProjectionReferences = cached
    require(isinstance(cached, tuple) and len(cached) == 2, 'REFERENCE_TREE_CHANGED')
    validate_references(*cached)
    return cached


def project_candidate(d, candidate_files, candidate_commit, candidate_tree):
    return project_files(candidate_files, *source_references(d), candidate_commit, candidate_tree)


def runtime_config_files(d, candidate_files, record):
    """Recompute from source before returning only non-business runtime config.

    The caller supplies the same immutable candidate archive used in building.
    The production stage never relies on a generated file or its record alone.
    """
    _validate_record(record)
    projected, expected = project_candidate(d, candidate_files, record['candidateCommit'], record['candidateTree'])
    require(record == expected, 'RECORD_SOURCE_CHANGED')
    return {name: projected[name] for name in RUNTIME_FILES}


def verify_output(files, record):
    _validate_record(record)
    rows = inventory(files)
    require(source_tree(files) == record['outputTree'] and fingerprint(rows) == record['outputFilesSha256']
            and all(rows.get(name) == row['after'] for name, row in record['generatedFiles'].items())
            and not (set(rows) & set(record['removedFiles'])), 'OUTPUT_CHANGED')
    return record


def verify_build_context(d, context, record):
    """Compare every build byte/mode to the immutable candidate's projection."""
    _validate_record(record)
    root = Path.cwd().resolve()
    context = Path(context)
    if not context.is_absolute():
        context = root / context
    require(context == root / CONTEXT_PATH and context.resolve() == context
            and context.is_dir() and not context.is_symlink(), 'CONTEXT_INVALID')
    candidate = d.registration_archive(d.registration_download(record['candidateCommit']),
                                       record['candidateCommit'])
    projected, expected = project_candidate(d, candidate, record['candidateCommit'], record['candidateTree'])
    require(record == expected, 'RECORD_SOURCE_CHANGED')
    actual = {}
    for path in context.rglob('*'):
        require(not path.is_symlink(), 'CONTEXT_INVALID')
        if path.is_dir():
            continue
        require(path.is_file() and path.stat().st_size <= 8 * 1024 * 1024
                and path.stat().st_mode & 0o7777 in (0o644, 0o755), 'CONTEXT_INVALID')
        actual[path.relative_to(context).as_posix()] = (
            path.read_bytes(), '100755' if path.stat().st_mode & 0o111 else '100644')
    require(actual == projected, 'CONTEXT_CHANGED')
    verify_output(actual, record)
    return record


def prepare_build(d):
    """Create one private build context; never modify the runner checkout."""
    require(os.environ.get('RELEASE_OPERATION') == 'release_api_workspace', 'SCOPE_CONFLICT')
    commit, tree = os.environ.get('RELEASE_COMMIT'), os.environ.get('SOURCE_TREE')
    require(isinstance(commit, str) and re.fullmatch(r'[a-f0-9]{40}', commit)
            and isinstance(tree, str) and re.fullmatch(r'[a-f0-9]{40}', tree)
            and d.run('git', 'rev-parse', 'HEAD') == commit
            and d.run('git', 'rev-parse', 'HEAD^{tree}') == tree, 'CANDIDATE_TREE_CHANGED')
    root = Path.cwd().resolve()
    target, record_path = root / CONTEXT_PATH, root / RECORD_PATH
    require(not target.exists() and not target.is_symlink()
            and not record_path.exists() and not record_path.is_symlink()
            and all(not path.is_symlink() for path in target.parents if path != root.parent),
            'OUTPUT_EXISTS')
    raw = subprocess.check_output(['git', 'archive', '--format=tar',
                                  '--prefix=id-business-system-' + commit + '/', commit], cwd=root)
    candidate = d.registration_archive(raw, commit)
    projected, record = project_candidate(d, candidate, commit, tree)
    verify_output(projected, record)
    target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    d.write_registration_files(target, projected)
    with record_path.open('x', encoding='utf-8') as stream:
        json.dump(record, stream, sort_keys=True)
    record_path.chmod(0o600)
    return record
