export const planLabels = {
  plus: 'ChatGPT Plus',
  'pro-5x': 'ChatGPT Pro 5×',
  'pro-20x': 'ChatGPT Pro 20×'
};
const labels: Record<string, string> = {
  free: '免费版',
  plus: 'Plus',
  pro: 'Pro（档位待核验）',
  running: '正在执行',
  awaiting_confirmation: '等待确认金额',
  confirming: '正在提交本次付款',
  finished: '本次操作已结束',
  unknown: '结果待核验',
  session_restore: '核对官网会话',
  session_verified: '账户核对通过',
  existing_checkout_read: '读取原结算',
  plan_selection: '选择官网套餐',
  quote_ready: '已取得官方报价',
  payment_ready: '已核价，等待确认',
  checkout_quote_verified: '官方报价已核对',
  blocked: '当前步骤未完成',
  subscription_activated: '开通成功',
  paid_pending_activation: '已付款，待开通',
  paid_tier_pending_verification: '已付款，档位待核验',
  payment_failed: '付款失败',
  payment_result_unknown: '付款结果待核验',
  verification_required: '需要本人网页或银行验证',
  payment_cancelled: '已取消本次确认',
  payment_submitted_or_pending: '等待原单付款结果',
  paid: '已确认付款',
  declined: '官方拒付',
  requires_action: '需要本人验证',
  not_attempted: '未尝试付款',
  not_verified: '未核验',
  restored: '会话已恢复',
  json_session_not_restored: 'JSON 会话未恢复，请提供新的授权 JSON',
  official_user_mismatch: '官网用户与 JSON 不一致',
  official_account_mismatch: '官网账户与 JSON 不一致',
  invalid_json: 'JSON 格式无效',
  missing_session_token: 'JSON 缺少官网会话凭据',
  browser_operation_failed: '官网浏览器步骤未完成',
  incompatible_existing_subscription: '已有不兼容订阅',
  previous_checkout_attempt_exists: '已有原结算记录，请复查原订单',
  previous_payment_attempt_exists: '该订单已尝试付款，只允许复查',
  account_has_other_payment_attempt: '该账户已有付款尝试，请选择原套餐复查',
  payment_quote_changed: '官网金额已变化，请重新核价',
  payment_confirmation_expired: '确认已过期，请重新核价',
  network_unconfirmed: '服务器出口未确认，暂不能提交付款',
  bank_verification_required: '需要本人完成银行验证',
  actual_quote_unknown: '无法明确读取今日应付',
  no_original_payment_attempt: '没有已尝试付款的原单',
  worker_operation_failed: '服务器执行步骤未完成',
  durable_state_unavailable: '记录服务未确认，已阻止重复请求',
  operation_cancelled: '操作已取消',
  http_error: '官网拒绝当前请求'
};
export function statusLabel(value: unknown) {
  return typeof value === 'string' ? (labels[value] ?? '待核验（可查看诊断码）') : '未知';
}
