CREATE TABLE `id_business_v2_google_sheets_sync` (
  `id` INTEGER NOT NULL DEFAULT 1,
  `enabled` BOOLEAN NOT NULL DEFAULT false,
  `google_oauth_client_id` VARCHAR(255) NULL,
  `client_secret_encrypted` TEXT NULL,
  `refresh_token_encrypted` TEXT NULL,
  `spreadsheet_id_encrypted` TEXT NULL,
  `oauth_state_hash` VARCHAR(64) NULL,
  `oauth_verifier_encrypted` TEXT NULL,
  `oauth_state_expires_at` DATETIME(6) NULL,
  `source_versions` JSON NOT NULL,
  `last_attempt_at` DATETIME(6) NULL,
  `last_succeeded_at` DATETIME(6) NULL,
  `last_error_code` VARCHAR(80) NULL,
  `last_error_message` VARCHAR(500) NULL,
  `run_lease_id` CHAR(36) NULL,
  `run_lease_expires_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_business_v2_google_sheets_sync_oauth_state_hash_key`(`oauth_state_hash`),
  INDEX `idbiz_google_sheets_enabled_attempt_idx`(`enabled`, `last_attempt_at`),
  INDEX `idbiz_google_sheets_oauth_expiry_idx`(`oauth_state_expires_at`),
  INDEX `idbiz_google_sheets_lease_expiry_idx`(`run_lease_expires_at`),
  CONSTRAINT `idbiz_google_sheets_singleton_check` CHECK (`id` = 1)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
